#include <iostream>
#include <fstream>
#include <string>
#include <vector>

using namespace std;

string arr_top[] = {
"; 64-bit \"Hello World!\" in Linux NASM               " ,
"global main                                           " ,
"                                                      " ,
"section .text                                         " ,
"main:                                                 " ,
"	; sys_write(stdout, message, length)           " ,
"	mov    rax, 1        ; sys_write               " ,
"	mov    rdi, 1        ; stdout                  " ,
"	mov    rsi, message_start                      " ,
"	mov    rdx, message_start_len                  " ,
"	syscall                                        " ,
"	;;;;;;;;;;;;;;;;;;;;;;;;                       " ,
"	                                               " 
};

string arr_bottom[] = {
"	                                               " ,
"	;;;;;;;;;;;;;;;;;;;;;;;                        " ,
"	; sys_write(stdout, message, length)           " ,
"	                                               " ,
"	mov    rax, 1        ; sys_write               " ,
"	mov    rdi, 1        ; stdout                  " ,
"	mov    rsi, message_finish                     " ,
"	mov    rdx, message_finish_len                 " ,
"	syscall                                        " ,
"	                                               " ,
"	; sys_exit(return_code)                        " ,
"	                                               " ,
"	mov    rax, 60        ; sys_exit               " ,
"	mov    rdi, 0        ; return 0 (success)      " ,
"	syscall                                        " ,
"                                                      " ,
"section .data                                         " ,
"message_start:		db '~~started..' ,0x0A         " ,
"message_start_len 	equ $-message_start            " ,
"                                                      " ,
"message_finish:	db '~~finished..',0x0A         " ,
"message_finish_len 	equ $-message_finish           " 
};

void run_instructions() {
	
	while( Linker::has_instruction() ) {
		wchar_t head = Linker::read_head();
		
		debug( "#! run_instructions" );
		debug( hex << head << dec );
		
		// unnecessary packing-unpacking into Instruct
		Instruct instruct = head_unpack(head);
		
		bool has_arg = instruct.has_arg();
		Code    code = instruct.code();
		Reg       r1 = instruct.r1();
		Reg       r2 = instruct.r2();
		Reg       r3 = instruct.r3();
		
		if( !has_arg ) {
			debug( "#! no arguments\n" );
			Linker::run_command_reg(code, r1, r2, r3);
		} else {
			debug( "#! has an argument\n" );
			int arg = Linker::read_arg();
			Linker::run_command_arg(code, r1, arg);
		}
	}
	
}

int main() {
	vector<string> template_top 	(arr_top, arr_top + sizeof arr_top / sizeof arr_top[0]);
	vector<string> template_bottom 	(arr_bottom, arr_bottom + sizeof arr_bottom / sizeof arr_bottom[0]);
	
	ofstream output("gen.asm");
	
	output << ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;" << endl;
	output << ";; this file was generated by generator.cpp" << endl;
	output << ";;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;" << endl;
	for ( vector<string>::const_iterator iter = template_top.begin();
			iter != template_top.end(); iter ++ ) {
		output << *iter << endl;	
	}
	////////////////////////////////
	// just change the registers someway
	output << "extern init" << endl;
	output << "extern run_command_arg" << endl;
	output << "extern run_command_reg" << endl;
	
	output << "	call init" << endl;
	///////////////////////////////
	
	
	
	
	/////////////////////////////////
	for ( vector<string>::const_iterator iter = template_bottom.begin();
			iter != template_bottom.end(); iter ++ ) {
		output << *iter << endl;	
	}
	
	return 0;
}

